# https://travis-ci.org/jleclanche/fireplace
sudo: false
language: python

python: "3.6"
cache: pip

env:
  - TOXENV=py36
  - TOXENV=flake8
  - TOXENV=benchmark

install:
  - pip install tox

script:
  - tox

notifications:
  email:
    on_failure: always
    on_success: change
  irc:
    channels:
      - "chat.freenode.net#hearthsim-commits"
    use_notice: true
    skip_join: true
    on_failure: always
    on_success: change
    template:
      - "(%{branch} @ %{commit} : %{author}): %{message} %{build_url}"
